---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netstat-server
spec:
  selector:
    matchLabels:
      app: netstat-server
  template:
    metadata:
      labels:
        app: netstat-server
    spec:
      hostNetwork: true
      enableServiceLinks: false
      imagePullSecrets:
        - name: regcred
      containers:
        - name: netstat-server
          image: netstat-server
          securityContext:
            privileged: true
          env:
            - name: PATH_PROCFS
              value: /host/proc
          ports:
            - containerPort: 3001
              name: http
          volumeMounts:
            - name: proc
              mountPath: /host/proc/
      securityContext:
        runAsUser: 0
      volumes:
      - name: proc
        hostPath:
          path: /proc/
---
apiVersion: v1
kind: Service
metadata:
  name: netstat-server
  labels:
    app: netstat-server
spec:
  clusterIP: None
  selector:
    app: netstat-server
  ports:
  - protocol: TCP
    port: 3001
    name: http
